// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: fan

#ifndef _FAN_UI_H
#define _FAN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
void fan_Animation(lv_obj_t * TargetObject, int delay);
extern lv_obj_t * ui_Screen1;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_normal_temperature_png);    // assets\normal temperature.png
LV_IMG_DECLARE(ui_img_high_temperature_png);    // assets\high temperature.png
LV_IMG_DECLARE(ui_img_fan2_png);    // assets\fan2.png
LV_IMG_DECLARE(ui_img_bar12_png);    // assets\bar12.png
LV_IMG_DECLARE(ui_img_bar1_png);    // assets\bar1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
